// <auto-generated />
using EF_lab4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_lab4.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250518144025_Initial_migration")]
    partial class Initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_lab4.Tables.Autorzy", b =>
                {
                    b.Property<int>("Id_Autora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Autora"));

                    b.Property<string>("Imię")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pochodzenie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Autora");

                    b.ToTable("Autorzy");
                });

            modelBuilder.Entity("EF_lab4.Tables.Książki", b =>
                {
                    b.Property<int>("Id_Ks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ks"));

                    b.Property<int>("AutorzyId_Autora")
                        .HasColumnType("int");

                    b.Property<int>("Id_Autora")
                        .HasColumnType("int");

                    b.Property<int>("Id_Wyd")
                        .HasColumnType("int");

                    b.Property<int>("Stan_ks")
                        .HasColumnType("int");

                    b.Property<int>("WydawnictwaId_Wyd")
                        .HasColumnType("int");

                    b.HasKey("Id_Ks");

                    b.HasIndex("AutorzyId_Autora");

                    b.HasIndex("WydawnictwaId_Wyd");

                    b.ToTable("Książki");
                });

            modelBuilder.Entity("EF_lab4.Tables.Wydawnictwa", b =>
                {
                    b.Property<int>("Id_Wyd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Wyd"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj_poch")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("aktywne")
                        .HasColumnType("bit");

                    b.Property<int>("rok_zal")
                        .HasColumnType("int");

                    b.HasKey("Id_Wyd");

                    b.ToTable("Wydawnictwa");
                });

            modelBuilder.Entity("EF_lab4.Tables.Książki", b =>
                {
                    b.HasOne("EF_lab4.Tables.Autorzy", "Autorzy")
                        .WithMany()
                        .HasForeignKey("AutorzyId_Autora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_lab4.Tables.Wydawnictwa", "Wydawnictwa")
                        .WithMany()
                        .HasForeignKey("WydawnictwaId_Wyd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorzy");

                    b.Navigation("Wydawnictwa");
                });
#pragma warning restore 612, 618
        }
    }
}
