// <auto-generated />
using EF_lab4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_lab4.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250530192855_Foriegn-Keys-fix")]
    partial class ForiegnKeysfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_lab4.Tables.Autorzy", b =>
                {
                    b.Property<int>("Id_Autora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Autora"));

                    b.Property<string>("Imię")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pochodzenie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Autora");

                    b.ToTable("Autorzy");

                    b.HasData(
                        new
                        {
                            Id_Autora = 1,
                            Imię = "Bolesław",
                            Nazwisko = "Prus",
                            Pochodzenie = "Polska"
                        },
                        new
                        {
                            Id_Autora = 2,
                            Imię = "Henryk",
                            Nazwisko = "Sienkiewicz",
                            Pochodzenie = "Polska"
                        },
                        new
                        {
                            Id_Autora = 3,
                            Imię = "Adam",
                            Nazwisko = "Mickiewicz",
                            Pochodzenie = "Polska"
                        });
                });

            modelBuilder.Entity("EF_lab4.Tables.Książki", b =>
                {
                    b.Property<int>("Id_Ks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ks"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stan_ks")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WydawnictwoId")
                        .HasColumnType("int");

                    b.HasKey("Id_Ks");

                    b.HasIndex("AutorId");

                    b.HasIndex("WydawnictwoId");

                    b.ToTable("Książki");

                    b.HasData(
                        new
                        {
                            Id_Ks = 1,
                            AutorId = 1,
                            Cena = 50.75m,
                            Stan_ks = 0,
                            Tytul = "Lalka",
                            WydawnictwoId = 1
                        },
                        new
                        {
                            Id_Ks = 2,
                            AutorId = 2,
                            Cena = 40.00m,
                            Stan_ks = 1,
                            Tytul = "Quo Vadis",
                            WydawnictwoId = 2
                        },
                        new
                        {
                            Id_Ks = 3,
                            AutorId = 3,
                            Cena = 45.50m,
                            Stan_ks = 0,
                            Tytul = "Pan Tadeusz",
                            WydawnictwoId = 3
                        },
                        new
                        {
                            Id_Ks = 4,
                            AutorId = 1,
                            Cena = 39.99m,
                            Stan_ks = 2,
                            Tytul = "Faraon",
                            WydawnictwoId = 1
                        });
                });

            modelBuilder.Entity("EF_lab4.Tables.Wydawnictwa", b =>
                {
                    b.Property<int>("Id_Wyd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Wyd"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj_poch")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("aktywne")
                        .HasColumnType("bit");

                    b.Property<int>("rok_zal")
                        .HasColumnType("int");

                    b.HasKey("Id_Wyd");

                    b.ToTable("Wydawnictwa");

                    b.HasData(
                        new
                        {
                            Id_Wyd = 1,
                            Adres = "Ludwika Mierosławskiego 11A",
                            Kraj_poch = "Polska",
                            Miasto = "Warszawa",
                            Nazwa = "Marginesy",
                            aktywne = true,
                            rok_zal = 2008
                        },
                        new
                        {
                            Id_Wyd = 2,
                            Adres = "ul. Kościuszki 10",
                            Kraj_poch = "Polska",
                            Miasto = "Kraków",
                            Nazwa = "Znak",
                            aktywne = true,
                            rok_zal = 1990
                        },
                        new
                        {
                            Id_Wyd = 3,
                            Adres = "ul. Mokotowska 3",
                            Kraj_poch = "Polska",
                            Miasto = "Warszawa",
                            Nazwa = "Czytelnik",
                            aktywne = true,
                            rok_zal = 1944
                        });
                });

            modelBuilder.Entity("EF_lab4.Tables.Książki", b =>
                {
                    b.HasOne("EF_lab4.Tables.Autorzy", "Autor")
                        .WithMany("Ksiażki")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_lab4.Tables.Wydawnictwa", "Wydawnictwo")
                        .WithMany("Ksiażki")
                        .HasForeignKey("WydawnictwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Wydawnictwo");
                });

            modelBuilder.Entity("EF_lab4.Tables.Autorzy", b =>
                {
                    b.Navigation("Ksiażki");
                });

            modelBuilder.Entity("EF_lab4.Tables.Wydawnictwa", b =>
                {
                    b.Navigation("Ksiażki");
                });
#pragma warning restore 612, 618
        }
    }
}
